### ISSUE TITLE
问一下archrepo2的作用。。

### ISSUE THREAD

**Issue by petronny** [lilydjwg/archrepo2#3]
如题。。
我看archrepo2会一直运行，它是每当有一个新的包放进目录的时候都自动repo-add吗？
另外是不是清理过期的包，不存在的包什么的都不是archrepo2管？

**Comment by lilydjwg** [comment]
On Thu, Sep 29, 2016 at 02:54:29AM -0700, Jingbei Li wrote:
> 如题。。
> 我看archrepo2会一直运行，它是每当有一个新的包放进目录的时候都自动repo-add吗？
> 另外是不是清理过期的包，不存在的包什么的都不是archrepo2管？

是的。它的作用就是维护 xxx.db 那个东西。也就是调用 repo-add
和 repo-remove，以及为 any 建立软链接、把包挪到正确的 $arch 目录。

清理过期包的脚本是
https://github.com/archlinuxcn/misc_scripts/blob/master/repocleaner

-- 
Best regards,
lilydjwg

Linux Vim Python 我的博客:
http://blog.lilydjwg.me/
-- 
A: Because it obfuscates the reading.
Q: Why is top posting so bad?

**Comment by petronny** [comment]
那lilac的config.ini中指定repo/x86_64
archrepo2的ini应该指定repo对吧。。
按理说lilac产生的新的包会触发archrepo2对吧。。
//我这里并没有触发。。我再查一查。。

另外为什么不用repo-add的-R选项来清理过期的包呢？

**Comment by lilydjwg** [comment]
On Thu, Sep 29, 2016 at 07:20:26AM -0700, Jingbei Li wrote:
> 那lilac的config.ini中指定repo/x86_64
> archrepo2的ini应该指定repo对吧。。
> 按理说lilac产生的新的包会触发archrepo2对吧。。
> //我这里并没有触发。。我再查一查。。
> 
> 另外为什么不用repo-add的-R选项来清理过期的包呢？

以前有这么个选项么？

有也没用啊，会保留一个版本的旧包的。

-- 
Best regards,
lilydjwg

Linux Vim Python 我的博客:
http://blog.lilydjwg.me/
-- 
A: Because it obfuscates the reading.
Q: Why is top posting so bad?

**Comment by petronny** [comment]
额。。。我写了一个repo-add.sh, 内容是
```
#!/bin/sh
repo-add -n -R $@
```
假设已经有testpkg-1.0-1了，当testpkg-1.1-1加入时，会出现类似下面的log
```
==> 正在添加软件包 'testpkg-1.1-1-x86_64.pkg.tar.xz'
  -> 正在添加软件包签名...
  -> 正在计算校验值...
  -> 正在删除现有的条目 'testpkg-1.0-1'...
  -> 正在创建 'desc' 数据库条目...
  -> 正在创建 'files' 数据库条目...
  -> 正在移除旧的软件包文件 'testpkg-1.0-1-x86_64.pkg.tar.xz'
[D 10-07 00:36:11.461 repomon:290] Removing: testpkg-1.0-1-x86_64.pkg.tar.xz
testpkg-1.0-1-x86_64.pkg.tar.xz remove None
testpkg-1.0 1
```
看起来挺正常的，但是接下来
```
[I 10-07 00:36:11.994 repomon:109] previous command done.
[I 10-07 00:36:11.994 repomon:93] Running cmd: ['repo-remove', 'test.db.tar.gz', 'testpkg']
==> 正在解压缩数据库到一个临时目录...
==> 正在解压缩数据库到一个临时目录...
==> 正在搜索软件包 'testpkg'...
  -> 正在删除现有的条目 'testpkg-1.1-1'...
```
貌似那个删除的动作被检测到了然后把最新的给删了。。。重复执行了一次`正在删除现有的条目`这个动作

**Comment by petronny** [comment]
还有一个问题，现在应该是靠pullpkg的文件操作来触发archrepo2检测lilac打出的包的
但是如果把archrepo2和lilac在同一个机器上，
且lilac中destdir[/somewhere/repo/any]
和archrepo2的path[/somewhere/repo]
指定的是同一个地方(如上)时，这时候不需要pullpkg了
但此时archrepo2检测不到lilac打出的包
是哪里出的问题呢。。

**Comment by lilydjwg** [comment]
因为 archrepo2 忘记了处理 CREATE 事件……

**Comment by lilydjwg** [comment]
删除的时候数据库还没更新，所以删除的时候删掉了最新版本的样子……

**Comment by lilydjwg** [comment]
> 但此时archrepo2检测不到lilac打出的包

已经修了，你试试看？

**Comment by petronny** [comment]
> > 但此时archrepo2检测不到lilac打出的包

> 已经修了，你试试看？

Ok, 这个看起来没问题了
